### ISSUE TITLE
Error when running em! : sparse not defined

### ISSUE THREAD

**Issue by arnaudmgh** [davidavdav/GaussianMixtures.jl#10]
**UPDATE**    
After looking at the code, there is a parameter `sparse` which is not described in the README.md. A quick fix is to add parameter `sparse = 0` in the call to `em!`.    

    julia> gmm = GMM(3, rand(1000, 2), method=:kmeans, kind=:full, nInit=50, nIter=10, nFinal=10);
    Iters               objv        objv-change | affected 
    -------------------------------------------------------------
      0       1.821018e+02
      1       7.313566e+01      -1.089661e+02 |        3
    ...
    K-means converged with 13 iterations (objv = 63.12602037657895)

    julia> em!(gmm, rand(1000, 2));
    ERROR: sparse not defined
 
I found a typo : sp**r**arse = 0 in `train.jl: 39`. Might it be the problem ?

**Comment by davidavdav** [comment]
Thanks.  The typo is definitively a problem.  However, that seems to be in the 1-dim data. 

As far as I remember, I didn't implement sparse training yet.
