### ISSUE TITLE
Support SpecialFunctions v2+?

### ISSUE THREAD

**Issue by ForceBru** [davidavdav/GaussianMixtures.jl#100]
I installed GaussianMixtures.jl, and SpecialFunctions.jl got downgraded significantly:

    ⌅ [276daf66] ↓ SpecialFunctions v2.1.7 ⇒ v1.8.7

Here it's required that SpecialFunctions be any version like `v1.?.?`:

https://github.com/davidavdav/GaussianMixtures.jl/blob/7480dd20646456c178636e8aadb17286b739f627/Project.toml#L36

However, versions 2.something are already out: https://github.com/JuliaMath/SpecialFunctions.jl/blob/36c547b4a270b6089b1baf7bec05707e9fb8c7f9/Project.toml#L1-L3.

Is it possible to support the new versions of SpecialFunctions.jl?

**Comment by davidavdav** [comment]
Hello, 

I think we need very little of special functions, but it needs to be tested that version 2 works.
