### ISSUE TITLE
wrong result sometimes.

### ISSUE THREAD

**Issue by 5tinzi** [davidavdav/GaussianMixtures.jl#102]
Thanks for this helpful packages, but I found it gives a wrong result in my data,  
have no idea if I run it properly, any suggetion for it? 

```julia 

using GaussianMixtures,CSV,DataFrames
X = CSV.read("test.csv",DataFrame) # the test.csv is upload 
X = Float32.(X.x)
# >X
# 272-element Vector{Float32}:
# 79.0
# 54.0
# ...

gmm = GMM(2,X)
```

then I get the result:
```julia
>gmm.μ
2×1 Matrix{Float32}:
 54.61786
 80.09303

>gmm.w
2-element Vector{Float32}:
 0.36097622
 0.6390237

>gmm.Σ
2×1 Matrix{Float32}:
 34.499268
 34.401367
```

but actully, it got a wrong result in gmm.Σ,  and compare to the result from a R pacakge call Mixtool,

```R
$lambda # same to gmm.w
[1] 0.3608498 0.6391502
$mu # same to gmm.μ
[1] 54.61364 80.09031
$sigma # GaussianMixtures got a wrong result here
[1] 5.869089 5.869089
```
the test data is upload: [test.csv](https://github.com/davidavdav/GaussianMixtures.jl/files/9558302/test.csv)

**Comment by 5tinzi** [comment]
I tried many times and found that I could not get good results,  and I always saw some bizarre peaks, as indicated by the arrows in the figure (the red lines in the figure represent the real Gaussian components, the green ones the inferred results by GaussianMixtures.jl).


![compare_result](https://user-images.githubusercontent.com/82663816/189955318-4e210ce0-f1cb-40f6-8b64-cd5100355f04.png)

Perhaps some charts to compare the results are helpful? Here is the code I used to generate the above results.
```julia
using Distributions, CairoMakie, GaussianMixtures

Random.seed!(125834)
G  = Figure()

for pic_i in 1:3, pic_j = 1:3

    # setting the true status
    peak_num = 3
    true_mu = rand(3) .* 2 
    true_sigma = rand(3) .* 2 

    a,b = rand(0:0.01:0.5,2)
    c = 1 - a - b
    true_w =  [a,b,c]  
    Inter_num = 2000

    mixN = MixtureModel(Normal, [ (i,j) for (i,j) in zip(true_mu,true_sigma)],  true_w )
    y = rand(mixN, 20000)
    p = Axis(G[pic_i,pic_j], title = "GMM peaks")
    density!(p, y, color = :gray)

    range_X = range(minimum(y), maximum(y),length=2000)
    peak1 = pdf.(Normal.( true_mu, true_sigma),  repeat( [range_X], peak_num )) .*  true_w
   
    for i in 1:length(peak1)
        lines!(p, range_X, peak1[i],color=:red,label="true peak$(i)")
    end

    gmm = GMM(3,y,nIter=Inter_num)

    peak2 = pdf.(Normal.(gmm.μ,gmm.Σ),  repeat( [range_X], peak_num ))  .* gmm.w
    for i in 1:length(peak2)
        lines!(p, range_X ,peak2[i], color=:green,label="GaussianMixtures peak$(i)")
    end
    # axislegend()
end

save("./compare_result.png",G,resolution=(1200,1000))
```

**Comment by davidavdav** [comment]
Hi, I think the confusion arises from that I store the covariance as a squared entity, i.e., a variance/covariance.   So if you have a diagonal covariance matrix, you need to `sqrt.()` that to get your R σs.

**Comment by 5tinzi** [comment]
Thanks for pointing that out, I hadn't noticed that before, problem solved. 

Have a nice day.
