### ISSUE TITLE
[Question] - how to calculate the BIC of a mixture model

### ISSUE THREAD

**Issue by 5tinzi** [davidavdav/GaussianMixtures.jl#103]
hi, 
I read the readme.md,  I wonder if  the "average log likelihood of the GMM given all data points" is equal to the  "log-likelihood of the model"?

I wanna calculate a  BIC , suppose  I fit a model `gmm = GMM(k,x)`,   
then  `BIC = −2 * loglik + (log N ) * d. `, where  loglik is the log-likelihood of the model,  N is the number of datapoints  and d is the number of parameters in the model.

so, is it OK to using `avll(gmm::GMM, x::Matrix)` as the loglik here?    

I am not an expert in the field of statistics, any advice is appreciated.

**Comment by davidavdav** [comment]
It has been a while since I've been working with BIC, but looking at [Wikipedia](https://en.wikipedia.org/wiki/Bayesian_information_criterion), your `loglik` is the total log-likelihood of the model, this would be `N * avll`.

**Comment by 5tinzi** [comment]
Thanks, it works as expected.

Have a nice day.
