### ISSUE TITLE
Cannot save array of GMM

### ISSUE THREAD

**Issue by arnaudmgh** [davidavdav/GaussianMixtures.jl#11]
Let me start by saying that the package is awesome.

I can save a GMM alone but not an array of GMMs:

    julia> GaussianMixtures.save(string(projdir, "nciRAS05.jl.output", "ggs1.jld"), "ggs1", ggs1[1]) # works fine
    
    julia> GaussianMixtures.save(string(projdir, "nciRAS05.jl.output", "ggs1.jld"), "ggs1", ggs1[1:2])  
     ERROR: type parameters with objects of type TypeConstructor are currently unsupported
     in full_typename at /PHShome/aa571/.julia/v0.3/HDF5/src/JLD.jl:893
     in full_typename at /PHShome/aa571/.julia/v0.3/HDF5/src/JLD.jl:848
     in full_typename at /PHShome/aa571/.julia/v0.3/HDF5/src/JLD.jl:861
     in full_typename at /PHShome/aa571/.julia/v0.3/HDF5/src/JLD.jl:920
     in full_typename at /PHShome/aa571/.julia/v0.3/HDF5/src/JLD.jl:930
     in _write at /PHShome/aa571/.julia/v0.3/HDF5/src/JLD.jl:540
     in write at /PHShome/aa571/.julia/v0.3/HDF5/src/JLD.jl:487 (repeats 2 times)
     in anonymous at /PHShome/aa571/.julia/v0.3/GaussianMixtures/src/io.jl:17
     in jldopen at /PHShome/aa571/.julia/v0.3/HDF5/src/JLD.jl:233
     in save at /PHShome/aa571/.julia/v0.3/GaussianMixtures/src/io.jl:15
    
    julia> typeof(ggs1)
    Array{GMM{T<:FloatingPoint,CT<:Union(Array{T,2},Array{T,1})},1}

**Comment by davidavdav** [comment]
Hi, 

How did you construct `ggs1`?  It might be the problem that the array type still is parameterized by `T` and `CT`, so this is not a concrete enough type to be saved I suppose. 

```julia
julia> typeof(gg)
Array{GMM{Float64,Array{Float64,2}},1}
julia> save("test.jld", "gmms", gg)
```

**Comment by arnaudmgh** [comment]
ggs1 = GMM[]
    for k in cellnames
      . . .
      push!(ggs1, GMM(4, facsda, method=:kmeans, kind=:full, nInit=50, nIter=10, nFinal=10))
    end

Would you know how I could declare the GMM array in order for it to be saved?

**Comment by davidavdav** [comment]
I am always having problems with this type of list construction.  You could re-construct the array after you've made it:

```julia
ggs1 = typeof(ggs1[1])[g for g in ggs1]
```

or, if you have an example gmm `g`, you can construct it beforehand:
```julia
ggs1 = typeof(g)[]
...
```
or, you can make it explicit, which is a it of a pain:
```julia
gss1 = GMM{Float64,Matrix{Float64}}[]
```
but you probably don't want to be concerned with the type dependencies of GMM.

**Comment by arnaudmgh** [comment]
Thank you very much David, the first option worked! It was very fast, so I might keep it, as it does not require specification of the type.

**Comment by arnaudmgh** [comment]
Just curious, do you have a preferred way of constructing lists ?

**Comment by davidavdav** [comment]
Yeah, it is a bit of a hack, and `ggs1` is probably not type-stabe, so you might want to separated it in a `tmp` on which you push, and then use `ggs1` to do the re-construction.  You don't have to worry about memory, as the GMM objects are not copied but just references in the list. 

I actually prefer the construction (afterwards)
```julia
ggs1 = vcat(ggs1...)
```
but I don't know if this gets very inefficient for large lists.

**Comment by arnaudmgh** [comment]
Oh, interesting notation, which actually seems to work in that case too; which reminds me I used to do reduce(vcat, ggs1) for DataFrame concatenation.

So would you also use `push!` in a `for` loop as I wrote above? Thank you, 
Arnaud

**Comment by davidavdav** [comment]
Yes, I think I would.  I like the comprehension like in `[compute_gmm(x) for x in array]` where compute_gmm() is some more complicated function.  But also comprehension tends to miss the exact type.

**Comment by arnaudmgh** [comment]
Great, thank you for the tips!
