### ISSUE TITLE
Test failure on 0.5

### ISSUE THREAD

**Issue by kpamnany** [davidavdav/GaussianMixtures.jl#16]
Does this package work on Julia 0.5? On both:

1. Julia Version 0.5.0-dev+2404
Commit 0e09b2a* (2016-01-29 19:54 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1
nothing

2. Julia Version 0.5.0-dev+2081
Commit 2335ef1c* (2016-01-11 18:21 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.3.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
nothing

``Pkg.test("GaussianMixtures")`` fails with the following error:
```
ERROR: LoadError: LoadError: MethodError: `xμTΛxμ!` has no method matching xμTΛxμ!(::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::UpperTriangular{Float64,Array{Flo
at64,2}})
Closest candidates are:
  xμTΛxμ!(::Array{T,2}, ::Array{T,2}, ::Array{T,2}, ::UpperTriangular{T,S<:AbstractArray{T,2}})
 [inlined code] from multidimensional.jl:186
 in llpg at /Users/kpamnany/.julia/v0.5/GaussianMixtures/src/train.jl:327
 in gmmposterior at /Users/kpamnany/.julia/v0.5/GaussianMixtures/src/train.jl:354
 in stats at /Users/kpamnany/.julia/v0.5/GaussianMixtures/src/stats.jl:85
 in stats at /Users/kpamnany/.julia/v0.5/GaussianMixtures/src/stats.jl:141
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in process_options at ./client.jl:245
 in _start at ./client.jl:301
while loading /Users/kpamnany/.julia/v0.5/GaussianMixtures/test/data.jl, in expression starting on line 29
while loading /Users/kpamnany/.julia/v0.5/GaussianMixtures/test/runtests.jl, in expression starting on line 5
```

**Comment by davidavdav** [comment]
Apparently not.  I didn't know 0.5 was out.   I will have to look at that.

**Comment by kpamnany** [comment]
0.5 is not released; I should have said Julia master.

**Comment by davidavdav** [comment]
See also #19
