### ISSUE TITLE
expected T<:Real, got Type{PDMats.PDMat{T<:Real,S<:AbstractArray{T,2}}}

### ISSUE THREAD

**Issue by jeff-regier** [davidavdav/GaussianMixtures.jl#19]
I'm having some trouble getting GaussianMixtures.jl working with Julia 0.5. Any suggestions for fixing this compile-time error?

```
ERROR: LoadError: LoadError: TypeError: MvNormal: in T, expected T<:Real, got Type{PDMats.PDMat{T<:Real,S<:AbstractArray{T,2}}}
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/jeff/.julia/v0.5/GaussianMixtures/src/distributions.jl, in expression starting on line 4
while loading /home/jeff/.julia/v0.5/GaussianMixtures/src/GaussianMixtures.jl, in expression starting on line 27
```

**Comment by jeff-regier** [comment]
I get pretty much the same error from Julia 0.4.6 too:
```
ERROR: LoadError: LoadError: TypeError: MvNormal: in T, expected T<:Real, got Type{PDMats.PDMat{T<:Real,S<:AbstractArray{T,2}}}
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/jeff/.julia/v0.4/GaussianMixtures/src/distributions.jl, in expression starting on line 4
```

**Comment by davidavdav** [comment]
Hi, 

It has been pretty frustrating to get GaussianMixtures working for 0.5.  I had it working, but I needed to patch a whole load of dependent packages.  In the end I submitted a whole set of PRs for those packages, but I don't know what the status is.  

I recollect that the packages was [passing the tests](https://travis-ci.org/davidavdav/GaussianMixtures.jl), at least for 0.4, but the badge state is weird.  

In this case, I suspect that `Distributions` has changed under my feet, or perhaps another dependent package. 

I'll have to look into that.

**Comment by jeff-regier** [comment]
Hi, thanks for the response. It may be PDMats that has changed. I can get rid of this error by doing 
```
Pkg.pin("PDMats", v"0.4.1")
```
anyway. That also rolls back the version of `Distributions`, now that you mention it, so perhaps it's the changes to `Distributions` are breaking.

**Comment by davidavdav** [comment]
Well, at least the stats people are busy with their packages, that is good news.  Now I just need to grasp the changes.  (The full covariance Gaussian Mixture should benefit from the PDMats infrastructure, but I've looked at it, and looked at it again and I can't see how.  This is probably a limitation on my side.)

**Comment by davidavdav** [comment]
Can we close this issue?  I think this has been resolved.
