### ISSUE TITLE
A way to adjust verbosity?

### ISSUE THREAD

**Issue by tawheeler** [davidavdav/GaussianMixtures.jl#20]
I am using the `GMM(n_components, data)` call which then prints a bunch of INFO commands, clustering results, etc. Is it possible for this to be optionally turned off? Something like `GMM(n_components, data, verbosity=:silent)` or `GMM(n_components, data, verbosity=Verbosity.DEBUG)`

**Comment by davidavdav** [comment]
Yes, there should be a way to pass these kind of options to GMM.  I am not a fan of passing trough loads of options from one call to the next.  Perhaps these kind of options should go in the GMM structure. 

Would be cool if there is a general logging framework.

**Comment by phaverty** [comment]
I would also be interested in turning off the messages

**Comment by phaverty** [comment]
Actually, it looks like the logic in train.jl for sending the logging level to Clustering.kmeans is backwards.  \lt should be \gt in both cases

**Comment by davidavdav** [comment]
This might finally have been fixed, by the above merge
