### ISSUE TITLE
GaussianMixtures not compiling under julia 0.6.2.1

### ISSUE THREAD

**Issue by mattcbro** [davidavdav/GaussianMixtures.jl#31]
I have Julia Pro installed on linux mint 18.3, 64 bits.  I can not use this module due to a compilation failure. The output follows:

julia> using GaussianMixtures
INFO: Precompiling module GaussianMixtures.

WARNING: deprecated syntax "typealias AbstractTriangular Triangular" at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/GaussianMixtures/src/compat.jl:5.
Use "const AbstractTriangular = Triangular" instead.

WARNING: deprecated syntax "typealias UpperTriangular{T,M} Triangular{T,M,:U,false}" at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/GaussianMixtures/src/compat.jl:6.
Use "UpperTriangular{T,M} = Triangular{T,M,:U,false}" instead.

WARNING: deprecated syntax "abstract GaussianMixture{T,CT}" at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/GaussianMixtures/src/gmmtypes.jl:37.
Use "abstract type GaussianMixture{T,CT} end" instead.

WARNING: deprecated syntax "typealias DiagCov{T} Matrix{T}" at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/GaussianMixtures/src/gmmtypes.jl:42.
Use "DiagCov{T} = Matrix{T}" instead.

WARNING: deprecated syntax "typealias FullCov{T} Vector{UpperTriangular{T,Matrix{T}}}" at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/GaussianMixtures/src/gmmtypes.jl:43.
Use "FullCov{T} = Vector{UpperTriangular{T,Matrix{T}}}" instead.

WARNING: deprecated syntax "typealias VecOrMat Union{Vector,Matrix}" at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/GaussianMixtures/src/gmmtypes.jl:45.
Use "const VecOrMat = Union{Vector,Matrix}" instead.

WARNING: deprecated syntax "typealias MatOrVecMat{T} Union{Matrix{T},Vector{Matrix{T}}}" at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/GaussianMixtures/src/gmmtypes.jl:46.
Use "MatOrVecMat{T} = Union{Matrix{T},Vector{Matrix{T}}}" instead.

WARNING: deprecated syntax "typealias DataOrMatrix{T} Union{Data{T},Matrix{T}}" at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/GaussianMixtures/src/gmmtypes.jl:204.
Use "DataOrMatrix{T} = Union{Data{T},Matrix{T}}" instead.

WARNING: deprecated syntax "inner constructor GMM(...) around /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/GaussianMixtures/src/gmmtypes.jl:69".
Use "GMM{T,CT}(...) where {T,CT}" instead.
ERROR: LoadError: LoadError: invalid subtyping in definition of VGMM
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/GaussianMixtures/src/gmmtypes.jl, in expression starting on line 521
while loading /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/GaussianMixtures/src/GaussianMixtures.jl, in expression starting on line 15
ERROR: Failed to precompile GaussianMixtures to /home/matt/.juliapro-0.6.2.1/lib/v0.6/GaussianMixtures.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
 [4] macro expansion at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/Atom/src/repl.jl:118 [inlined]
 [5] anonymous at ./<missing>:?

**Comment by davidavdav** [comment]
Thank, yes, I am aware of that, but I am having a really hard time getting the type dispatch work as it did for julia-0.5 and below

**Comment by mattcbro** [comment]
Hmm that's odd.  Is it a Julia issue then?  I've resorted to rolling my own Gaussian mixture tool,  but it's annoying and error prone reinventing the wheel.

**Comment by davidavdav** [comment]
OK, with the merge of #29 the package at least passes the test on my own machine again.

**Comment by pgbarletta** [comment]
Passing by to inform that while it fails to build on Julia v0.6.0.0. It compiles fine on v0.6.3. 
Just a couple of warnings about overloading the Base `info(Any)`  method

**Comment by davidavdav** [comment]
OK, great.  I am not going to study the differences between 0.6.0.0 and 0.6.3, and close this issue for now.
