### ISSUE TITLE
Cannot add for Julia v1.0.2

### ISSUE THREAD

**Issue by BoundaryValueProblems** [davidavdav/GaussianMixtures.jl#35]
I tried to add this package under the latest Julia v1.0.2, but failed as follows:
```
(v1.0) pkg> add GaussianMixtures
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package GaussianMixtures [cc18c42c]:
 GaussianMixtures [cc18c42c] log:
 ├─possible versions are: [0.0.1-0.0.12, 0.1.0, 0.2.0] or uninstalled
 ├─restricted to versions 0.0.0-* by an explicit requirement, leaving only versions [0.0.1-0.0.12, 0.1.0, 0.2.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```
It would be great if this package is updated for Julia v1.0.x. Thanks!

**Comment by BoundaryValueProblems** [comment]
My posting above was for the tagged version v0.2.0 of GaussianMixtures.jl. I just added the current master branch. Then, it worked, i.e., I could install it and ran the package test successfully! Thanks! When the master branch will be tagged to be an official release?

**Comment by davidavdav** [comment]
Yes, that would probably be a good idea.  I'll see how easy that is nowadays.

**Comment by davidavdav** [comment]
Fixed in https://github.com/JuliaLang/METADATA.jl/pull/19439.

**Comment by BoundaryValueProblems** [comment]
Thanks a lot, @davidavdav !
