### ISSUE TITLE
[Feature] Automatic exit from EM phase by threshold?

### ISSUE THREAD

**Issue by AmebaBrain** [davidavdav/GaussianMixtures.jl#37]
Dear all, 
At first, thanks for a great package

I have a question for EM phase. Now, it neither automatically exit on some predefined log probability change threshold nor allows to specify it as a parameter.

I've created small [demo](https://gist.github.com/AmebaBrain/8cd130a1b0873fc5bae9b9fc5ed17530) for trivial input data with 5 clusters in 2d space.

It can be clearly seen, that K-means did all the job and average log likelihood **doesn't** change from the very first iteration. I.e. it's constant -2.222456

Does it make sense for such cases to automatically stop EM process and say that model doesn't progress further?

Also, it would be great to have possibility to set such threshold as input parameter for GMM model constructor

Many thanks

**Comment by davidavdav** [comment]
Yes, I suppose this would make sense.  I've never needed it myself, but there definitely will be applications where it is useful.  I suppose you can always just do a single iteration and inspect the average log likelihood yourself and decide.   The hardest part  of implementation would be to decide on the right interface: would you look at change, or at absolute value, or at relative change, how would the condition be combined with number of iterations (and, or, ..), etc.

**Comment by AmebaBrain** [comment]
ahh, got it
I re-wrote test [example](https://gist.github.com/AmebaBrain/8cd130a1b0873fc5bae9b9fc5ed17530) and added conditional exit by log likelihood delta change

You are also right that exit criteria will be different for different cases. Because we have exit mechanism via `em!` method, I think this feature request could be closed. 

Many thanks!
