### ISSUE TITLE
test GaussianMixtures throws an error in train.jl

### ISSUE THREAD

**Issue by finmod** [davidavdav/GaussianMixtures.jl#40]
Just installed GaussianMixtures v0.3.0 and tried > test GaussianMixtures. It fails with the following error message during the testing of train.jl:

 @ GaussianMixtures C:\Users\Denis\.julia\packages\GaussianMixtures\RGtTJ\src\train.jl:255
[ Info: iteration 10, average log likelihood -1.065560
┌ Info: EM with 100000 data points 10 iterations avll -1.065560
└ 59.0 data points per parameter

Unreachable reached at 000000001F37E07B

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ILLEGAL_INSTRUCTION at 0x1f37e07b -- top-level scope at C:\Users\Denis\.julia\packages\GaussianMixtures\RGtTJ\test\train.jl:32 [inlined]
top-level scope at .\none:0
in expression starting at C:\Users\Denis\.julia\packages\GaussianMixtures\RGtTJ\test\train.jl:22
top-level scope at C:\Users\Denis\.julia\packages\GaussianMixtures\RGtTJ\test\train.jl:32 [inlined]
top-level scope at .\none:0
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1864
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:758
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win64/build/src\ast.c:883
jl_load at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:826 [inlined]
jl_load_ at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:833
include at .\boot.jl:326 [inlined]
include_relative at .\loading.jl:1038
include at .\sysimg.jl:29
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
include at .\client.jl:403
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:323
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:411
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:362 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:755
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:885
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 00000000088B2A3F)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:764
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win64/build/src\ast.c:883
jl_load at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:826 [inlined]
jl_load_ at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:833
include at .\boot.jl:326 [inlined]
include_relative at .\loading.jl:1038
include at .\sysimg.jl:29
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
include at .\client.jl:403
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1864
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:323
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:411
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:362 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:755
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:885
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 0000000005B1C6EF)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:764
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:713
jl_toplevel_eval at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:773 [inlined]
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:793
eval at .\boot.jl:328
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
exec_options at .\client.jl:243
_start at .\client.jl:436
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
true_main at /home/Administrator/buildbot/worker/package_win64/build/ui\repl.c:96
wmain at /home/Administrator/buildbot/worker/package_win64/build/ui\repl.c:217
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:329
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:212
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 160604496 (Pool: 160377260; Big: 227236); GC: 1003
ERROR: Package GaussianMixtures errored during testing

**Comment by davidavdav** [comment]
Thanks for reporting this.  I've noticed that this package doesn't pass the test any more, giving these kind of errors.  An illegal instruction definitely seems to be a Julia issue, or perhaps a llvm issue, but in the current test it is hard to pinpoint where things go wrong.

**Comment by floswald** [comment]
tests seem to pass on this PR now after an update of dependencies: https://github.com/davidavdav/GaussianMixtures.jl/pull/42

**Comment by davidavdav** [comment]
Thanks for fixing this.  I hope the package is actually useful to you, I am not using it myself really (hence the bad maintainance...).  It is also one of my first Julia packages, so the code style hurts my eyes a bit when I look at it (not that I've become much better at coding, though...)

**Comment by floswald** [comment]
i think i'd *like* to use it. I have a research project where I want to implement an EM algorithm with a slightly different M-step (the likelihood for that model has 2 parts, one standard gaussian and another part related to switching states). I looked at R and [mixtools](https://cran.r-project.org/web/packages/mixtools/index.html) but it's a hell of illegible c code, so impossible to extend. I found your setup quite fast (compared to my naive hand coded version) - really now should benchmark against a simple R data.table implementation and see how that fares.

In general, I think this is a pretty important package for the community, so someone should maintain it (I understand of course if that's not your first priority :wink:) 
relatedly - would it be ok if i ask you the odd question about how you did what every once in a while? thanks.

**Comment by davidavdav** [comment]
Yes, sure, fire away.  I used to do big time (as in large models an for many years) GMM training when I still was working in the speaker recognition field, so this packages is somewhat geared towards massive parallel computation of diag cov GMMs, later I put in full cov and variational Bayes---the latter was more like a coding exercise, but it seems it got most traction, "most" having not so much meaning for a <100 star repo...
