### ISSUE TITLE
Calling em! vs GMM

### ISSUE THREAD

**Issue by victorgarciareolid** [davidavdav/GaussianMixtures.jl#65]
Hi,
Before anything let me know you that I starting using Julia (v. 1.4.1) and I may have not grounded some very basic concepts yet but here goes my question:
I'm trying to fit the mixture using the following line of code:
``` model = GMM(n_mixtures, features_reduced)```
This provide reasonable results (different values of posterior probabilities).
However, I tried those lines bellow that in my opinion should provide the same results.
```
model = GMM(n_mixtures, size(features_reduced, 2), kind=:full);
em!(model, features_reduced, nIter = 10, varfloor=1e-3)
```
This produces the following posterior probabilities:
```
100×3 Array{Float64,2}:
 0.333333  0.333333  0.333333
 0.333333  0.333333  0.333333
 0.333333  0.333333  0.333333
 0.333333  0.333333  0.333333
 ⋮                   
 0.333333  0.333333  0.333333
 0.333333  0.333333  0.333333
 0.333333  0.333333  0.333333
```

Thank you very much.

**Comment by davidavdav** [comment]
I think this is the same as #64 , you can use an initializer with the data, that will first do a kmeans clustering

**Comment by victorgarciareolid** [comment]
Yes sorry for duplicated!
