### ISSUE TITLE
Feature Request: MixtureModel(gmm) with univariate gmm should produce univariate MixtureModel

### ISSUE THREAD

**Issue by tawheeler** [davidavdav/GaussianMixtures.jl#7]
The current implementation of MixtureModel produces a multivariate MixtureModel for univariate GMMs.
Would it be possible to automatically covert to Univariate distributions instead?

```
gmm = GMM(2, vcat(randn(100), randn(50)+1), nIter=10)
mm = MixtureModel(gmm)
@assert(typeof(mm) <: Distribution{Univariate})
```

```
ERROR: assertion failed: typeof(mm) <: Distribution{Univariate}
```

Thanks!

**Comment by davidavdav** [comment]
Thanks for the suggestion, this should work now.\
